### PR TITLE
Add storybook configuration and example

### PR DESCRIPTION
**Pull request by fgkolf**
Added basic storybook configuration along with an example based on the application's code.
Do you think i should add details in README about storybook's related scripts?

### CODE REVIEW

**Review by lenmorld — APPROVED** [review]
Awesome! 🥇
Tested it out and it works!

Yes if you can add some details o the README, that's great too
but I'll approve this one now 👍

**Comment by lenmorld** [comment]
@fgkolf When you get the chance, please fix the conflicts and merge it.
Thank you!

**Comment by fgkolf** [comment]
> @fgkolf When you get the chance, please fix the conflicts and merge it.
> Thank you!

Sure @lenmorld, will fix this in the next few days.

**Comment by fgkolf** [comment]
@lenmorld Updated the PR, resolved conflicts, added README instructions for storybook

**Comment by lenmorld** [comment]
Awesome! thanks for your contribution!

**Review by lenmorld — APPROVED** [review]

**Pull request merged**
